const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

function buildRusticBlueprintHTML() {
  const bgPath = path.resolve('e:\\USER\\Downloads\\Edvankar\\qwikamp\\rustic_paper_bg.jpg');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Qwikamp — System Overview & Core Information Architecture</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@500;600;700&family=Space+Grotesk:wght@500;600;700&display=swap');

    * {
      box-sizing: border-box;
      margin: 0;
      padding: 0;
    }

    body {
      background-color: #0C0E12;
      width: 2560px;
      height: 1440px;
      position: relative;
      overflow: hidden;
      display: flex;
      align-items: center;
      justify-content: center;
      font-family: 'Space Grotesk', -apple-system, BlinkMacSystemFont, sans-serif;
      -webkit-font-smoothing: antialiased;
    }

    /* Photographic rustic paper background generated by Nano Banana */
    .bg-image {
      position: absolute;
      inset: 0;
      width: 100%;
      height: 100%;
      object-fit: fill;
      z-index: 1;
    }

    /* Diagram Canvas aligned directly to the paper sheet bounds */
    .paper-canvas {
      position: absolute;
      top: 85px;
      bottom: 85px;
      left: 310px;
      right: 310px;
      z-index: 10;
      mix-blend-mode: multiply;
      display: flex;
      flex-direction: column;
    }

    svg.blueprint-svg {
      width: 100%;
      height: 100%;
    }

    .font-mono { font-family: 'JetBrains Mono', Consolas, monospace; }
    .font-sans { font-family: 'Space Grotesk', -apple-system, BlinkMacSystemFont, sans-serif; }
  </style>
</head>
<body>

  <!-- AI Generated Rustic Paper Background -->
  <img class="bg-image" src="file:///${bgPath.replace(/\\/g, '/')}" />

  <!-- Diagram Overlay -->
  <div class="paper-canvas">
    <svg class="blueprint-svg" viewBox="0 0 1940 1270" xmlns="http://www.w3.org/2000/svg">
      <defs>
        <!-- Crisp Graphite Arrow Marker -->
        <marker id="arrow" viewBox="0 0 10 10" refX="7" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse">
          <path d="M 0 1.5 L 8 5 L 0 8.5 z" fill="#221C16"/>
        </marker>
      </defs>

      <!-- ══════════════════════════════════════════════════════════════════
           1. TOP HEADER (Simple Architectural Title)
           ══════════════════════════════════════════════════════════════════ -->
      <g transform="translate(20, 36)">
        <text x="0" y="0" class="font-sans" font-size="20" font-weight="700" fill="#221C16" letter-spacing="-0.3">
          QWIKAMP — SYSTEM OVERVIEW &amp; CORE INFORMATION ARCHITECTURE
        </text>
        <text x="0" y="20" class="font-mono" font-size="10.5" font-weight="600" fill="#5C4D39">
          Spec: UI_UX_INFORMATION_ARCHITECTURE.md (§ 1.0) • Flowchart Topology (Mermaid Graph TD)
        </text>
        <line x1="0" y1="32" x2="1900" y2="32" stroke="#6E5A42" stroke-width="1.2" opacity="0.6"/>
      </g>

      <!-- ══════════════════════════════════════════════════════════════════
           2. AUTH & ONBOARDING STREAM (Top Row Flow)
           A -> B -> C -> D
           ══════════════════════════════════════════════════════════════════ -->

      <!-- Node A: Onboarding Screen Carousel -->
      <g transform="translate(200, 115)">
        <rect x="0" y="0" width="260" height="48" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
        <text x="130" y="30" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
          Onboarding Screen Carousel
        </text>
      </g>

      <!-- Arrow A -> B -->
      <line x1="460" y1="139" x2="550" y2="139" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>

      <!-- Node B: Login Screen -->
      <g transform="translate(550, 115)">
        <rect x="0" y="0" width="220" height="48" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
        <text x="110" y="30" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
          Login Screen
        </text>
      </g>

      <!-- Arrow B -> C -->
      <line x1="770" y1="139" x2="860" y2="139" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>

      <!-- Node C: Verification / OTP Screen -->
      <g transform="translate(860, 115)">
        <rect x="0" y="0" width="250" height="48" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
        <text x="125" y="30" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
          Verification / OTP Screen
        </text>
      </g>

      <!-- Arrow C -> D -->
      <line x1="1110" y1="139" x2="1200" y2="139" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>

      <!-- Node D: Home Page - Light & Dark Modes (Central Hub) -->
      <g transform="translate(1200, 111)">
        <rect x="0" y="0" width="320" height="56" rx="4" fill="#221C16" stroke="#221C16" stroke-width="1.8"/>
        <text x="160" y="34" class="font-sans" font-size="14.5" font-weight="700" fill="#F4EFE2" text-anchor="middle">
          Home Page - Light &amp; Dark Modes
        </text>
      </g>

      <!-- ══════════════════════════════════════════════════════════════════
           3. SUBGRAPH 1: Nav_Entry ["Home Navigation & Entry Points"]
           ══════════════════════════════════════════════════════════════════ -->
      <g transform="translate(20, 230)">
        <!-- Subgraph Container Box -->
        <rect x="0" y="0" width="1900" height="205" rx="6" fill="rgba(60,45,25,0.025)" stroke="#524534" stroke-width="1.6" stroke-dasharray="7 5"/>
        
        <!-- Subgraph Title Tag -->
        <g transform="translate(24, 0)">
          <rect x="0" y="-12" width="290" height="22" rx="3" fill="#E2D7BD" stroke="#8C795E" stroke-width="1"/>
          <text x="145" y="4" class="font-mono" font-size="11" font-weight="700" fill="#2B2319" text-anchor="middle" letter-spacing="0.5">
            HOME NAVIGATION &amp; ENTRY POINTS
          </text>
        </g>

        <!-- 6 Navigation Nodes -->
        <!-- Node E: Shop Page -->
        <g id="node-E" transform="translate(30, 115)">
          <rect x="0" y="0" width="270" height="54" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="135" y="33" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
            Shop Page
          </text>
        </g>

        <!-- Node F: Repair Page - Service Center Map -->
        <g id="node-F" transform="translate(340, 115)">
          <rect x="0" y="0" width="280" height="54" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="140" y="33" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
            Repair Page - Service Center Map
          </text>
        </g>

        <!-- Node G: Service Your Cycle Page -->
        <g id="node-G" transform="translate(660, 115)">
          <rect x="0" y="0" width="270" height="54" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="135" y="33" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
            Service Your Cycle Page
          </text>
        </g>

        <!-- Node H: Doorstep Repair Page -->
        <g id="node-H" transform="translate(970, 115)">
          <rect x="0" y="0" width="270" height="54" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="135" y="33" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
            Doorstep Repair Page
          </text>
        </g>

        <!-- Node I: Cart Page -->
        <g id="node-I" transform="translate(1280, 115)">
          <rect x="0" y="0" width="270" height="54" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="135" y="33" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
            Cart Page
          </text>
        </g>

        <!-- Node J: Profile Page -->
        <g id="node-J" transform="translate(1590, 115)">
          <rect x="0" y="0" width="280" height="54" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="140" y="33" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
            Profile Page
          </text>
        </g>
      </g>

      <!-- ══════════════════════════════════════════════════════════════════
           CONNECTORS: D -> E, F, G, H, I, J (with edge labels)
           ══════════════════════════════════════════════════════════════════ -->
      <!-- Trunk down from D: (1360, 167) -->
      <path d="M 1360 167 L 1360 205 L 1000 205 L 1000 230" stroke="#241E18" stroke-width="1.8" fill="none"/>
      
      <!-- Distribution Bus Line at Y = 305 -->
      <path d="M 185 305 L 1750 305" stroke="#241E18" stroke-width="1.8" fill="none"/>
      <line x1="1000" y1="230" x2="1000" y2="305" stroke="#241E18" stroke-width="1.8"/>

      <!-- Drops into the 6 Nodes -->
      <!-- Drop to E -->
      <line x1="185" y1="305" x2="185" y2="345" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>
      <g transform="translate(185, 325)">
        <rect x="-80" y="-10" width="160" height="20" rx="3" fill="#F8F3E5" stroke="#8C795E" stroke-width="1"/>
        <text x="0" y="4" class="font-mono" font-size="9.5" font-weight="600" fill="#352B1E" text-anchor="middle">Navbar / Hero / 2x2 Grid</text>
      </g>

      <!-- Drop to F -->
      <line x1="500" y1="305" x2="500" y2="345" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>
      <g transform="translate(500, 325)">
        <rect x="-80" y="-10" width="160" height="20" rx="3" fill="#F8F3E5" stroke="#8C795E" stroke-width="1"/>
        <text x="0" y="4" class="font-mono" font-size="9.5" font-weight="600" fill="#352B1E" text-anchor="middle">Navbar / Hero / 2x2 Grid</text>
      </g>

      <!-- Drop to G -->
      <line x1="815" y1="305" x2="815" y2="345" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>
      <g transform="translate(815, 325)">
        <rect x="-65" y="-10" width="130" height="20" rx="3" fill="#F8F3E5" stroke="#8C795E" stroke-width="1"/>
        <text x="0" y="4" class="font-mono" font-size="9.5" font-weight="600" fill="#352B1E" text-anchor="middle">2x2 Grid / Services</text>
      </g>

      <!-- Drop to H -->
      <line x1="1125" y1="305" x2="1125" y2="345" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>
      <g transform="translate(1125, 325)">
        <rect x="-65" y="-10" width="130" height="20" rx="3" fill="#F8F3E5" stroke="#8C795E" stroke-width="1"/>
        <text x="0" y="4" class="font-mono" font-size="9.5" font-weight="600" fill="#352B1E" text-anchor="middle">2x2 Grid / Services</text>
      </g>

      <!-- Drop to I -->
      <line x1="1435" y1="305" x2="1435" y2="345" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>
      <g transform="translate(1435, 325)">
        <rect x="-80" y="-10" width="160" height="20" rx="3" fill="#F8F3E5" stroke="#8C795E" stroke-width="1"/>
        <text x="0" y="4" class="font-mono" font-size="9.5" font-weight="600" fill="#352B1E" text-anchor="middle">Navbar Icon / Bottom Bar</text>
      </g>

      <!-- Drop to J -->
      <line x1="1750" y1="305" x2="1750" y2="345" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>
      <g transform="translate(1750, 325)">
        <rect x="-80" y="-10" width="160" height="20" rx="3" fill="#F8F3E5" stroke="#8C795E" stroke-width="1"/>
        <text x="0" y="4" class="font-mono" font-size="9.5" font-weight="600" fill="#352B1E" text-anchor="middle">Navbar Icon / Bottom Bar</text>
      </g>

      <!-- ══════════════════════════════════════════════════════════════════
           4. SUBGRAPH 2: Cart_Panels ["Cart Page - Unified Management (4 Panels)"]
           ══════════════════════════════════════════════════════════════════ -->
      <g transform="translate(880, 490)">
        <!-- Subgraph Container Box -->
        <rect x="0" y="0" width="1040" height="180" rx="6" fill="rgba(60,45,25,0.025)" stroke="#524534" stroke-width="1.6" stroke-dasharray="7 5"/>
        
        <!-- Subgraph Title Tag -->
        <g transform="translate(24, 0)">
          <rect x="0" y="-12" width="370" height="22" rx="3" fill="#E2D7BD" stroke="#8C795E" stroke-width="1"/>
          <text x="185" y="4" class="font-mono" font-size="11" font-weight="700" fill="#2B2319" text-anchor="middle" letter-spacing="0.5">
            CART PAGE - UNIFIED MANAGEMENT (4 PANELS)
          </text>
        </g>

        <!-- 4 Cart Panels -->
        <!-- Node I1: Purchases Panel -->
        <g id="node-I1" transform="translate(25, 85)">
          <rect x="0" y="0" width="225" height="52" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="112.5" y="32" class="font-sans" font-size="13" font-weight="600" fill="#1C1813" text-anchor="middle">
            Purchases Panel
          </text>
        </g>

        <!-- Node I2: Repair Panel -->
        <g id="node-I2" transform="translate(275, 85)">
          <rect x="0" y="0" width="225" height="52" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="112.5" y="32" class="font-sans" font-size="13" font-weight="600" fill="#1C1813" text-anchor="middle">
            Repair Panel
          </text>
        </g>

        <!-- Node I3: Service Panel -->
        <g id="node-I3" transform="translate(525, 85)">
          <rect x="0" y="0" width="225" height="52" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="112.5" y="32" class="font-sans" font-size="13" font-weight="600" fill="#1C1813" text-anchor="middle">
            Service Panel
          </text>
        </g>

        <!-- Node I4: Doorstep Panel -->
        <g id="node-I4" transform="translate(775, 85)">
          <rect x="0" y="0" width="235" height="52" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="117.5" y="32" class="font-sans" font-size="13" font-weight="600" fill="#1C1813" text-anchor="middle">
            Doorstep Panel
          </text>
        </g>
      </g>

      <!-- Connection from I (Cart Page) to Cart Panels: I -> I1, I2, I3, I4 -->
      <!-- I bottom: (1435, 399) -->
      <path d="M 1435 399 L 1435 445 L 1400 445 L 1400 535" stroke="#241E18" stroke-width="1.8" fill="none"/>
      
      <!-- Bus for Cart Panels at Y = 535 -->
      <path d="M 1017 535 L 1772 535" stroke="#241E18" stroke-width="1.8" fill="none"/>
      
      <!-- Drops into I1, I2, I3, I4 -->
      <line x1="1017" y1="535" x2="1017" y2="575" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>
      <line x1="1267" y1="535" x2="1267" y2="575" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>
      <line x1="1517" y1="535" x2="1517" y2="575" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>
      <line x1="1772" y1="535" x2="1772" y2="575" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>

      <!-- ══════════════════════════════════════════════════════════════════
           5. SUBGRAPH 3: Secondary_Screens ["Detailed Views & Modal Overlays"]
           ══════════════════════════════════════════════════════════════════ -->
      <g transform="translate(20, 730)">
        <!-- Subgraph Container Box -->
        <rect x="0" y="0" width="1900" height="460" rx="6" fill="rgba(60,45,25,0.025)" stroke="#524534" stroke-width="1.6" stroke-dasharray="7 5"/>
        
        <!-- Subgraph Title Tag -->
        <g transform="translate(24, 0)">
          <rect x="0" y="-12" width="310" height="22" rx="3" fill="#E2D7BD" stroke="#8C795E" stroke-width="1"/>
          <text x="155" y="4" class="font-mono" font-size="11" font-weight="700" fill="#2B2319" text-anchor="middle" letter-spacing="0.5">
            DETAILED VIEWS &amp; MODAL OVERLAYS
          </text>
        </g>

        <!-- Node E1: Product Details Page -->
        <g id="node-E1" transform="translate(30, 80)">
          <rect x="0" y="0" width="270" height="56" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="135" y="34" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
            Product Details Page
          </text>
        </g>

        <!-- Arrow E1 -> E2 -->
        <line x1="165" y1="136" x2="165" y2="225" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>

        <!-- Node E2: Payment Success Screen -->
        <g id="node-E2" transform="translate(30, 225)">
          <rect x="0" y="0" width="270" height="56" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="135" y="34" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
            Payment Success Screen
          </text>
        </g>

        <!-- Node F1: Extended Service Center Page -->
        <g id="node-F1" transform="translate(340, 80)">
          <rect x="0" y="0" width="280" height="56" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="1.8"/>
          <text x="140" y="34" class="font-sans" font-size="13.5" font-weight="600" fill="#1C1813" text-anchor="middle">
            Extended Service Center Page
          </text>
        </g>

        <!-- Node K: Bill View / Invoice Sheet (Modal Overlay) -->
        <g id="node-K" transform="translate(940, 150)">
          <rect x="0" y="0" width="680" height="68" rx="4" fill="#F8F3E5" stroke="#241E18" stroke-width="2"/>
          <text x="340" y="41" class="font-sans" font-size="15.5" font-weight="700" fill="#1C1813" text-anchor="middle">
            Bill View / Invoice Sheet
          </text>
        </g>
      </g>

      <!-- ══════════════════════════════════════════════════════════════════
           CONNECTORS INTO SECONDARY SCREENS
           ══════════════════════════════════════════════════════════════════ -->
      <!-- Arrow E -> E1: from E bottom (185, 399) down to E1 top (185, 810) -->
      <line x1="185" y1="399" x2="185" y2="810" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>

      <!-- Arrow F -> F1: from F bottom (500, 399) down to F1 top (500, 810) -->
      <line x1="500" y1="399" x2="500" y2="810" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>

      <!-- Connections from I1, I2, I3, I4 -> K -->
      <!-- I1 bottom (1017, 627) -->
      <!-- I2 bottom (1267, 627) -->
      <!-- I3 bottom (1517, 627) -->
      <!-- I4 bottom (1772, 627) -->
      <!-- Collector bus at Y = 780 -->
      <path d="M 1017 627 L 1017 780" stroke="#241E18" stroke-width="1.6" fill="none"/>
      <path d="M 1267 627 L 1267 780" stroke="#241E18" stroke-width="1.6" fill="none"/>
      <path d="M 1517 627 L 1517 780" stroke="#241E18" stroke-width="1.6" fill="none"/>
      <path d="M 1772 627 L 1772 780" stroke="#241E18" stroke-width="1.6" fill="none"/>
      
      <!-- Bus horizontal line at Y = 780 -->
      <path d="M 1017 780 L 1772 780" stroke="#241E18" stroke-width="1.6" fill="none"/>

      <!-- Drop into K (center 1300, 880) -->
      <line x1="1300" y1="780" x2="1300" y2="880" stroke="#241E18" stroke-width="1.8" marker-end="url(#arrow)"/>

    </svg>
  </div>

</body>
</html>`;
}

async function run() {
  const htmlContent = buildRusticBlueprintHTML();
  const htmlPath = path.resolve('e:\\USER\\Downloads\\Edvankar\\qwikamp\\diagram_1_rustic_overlay.html');
  fs.writeFileSync(htmlPath, htmlContent, 'utf-8');
  console.log('Saved rustic overlay HTML to:', htmlPath);

  const outPng1 = path.resolve('e:\\USER\\Downloads\\Edvankar\\qwikamp\\diagram_1_system_overview_blueprint.png');
  const outPng2 = path.resolve('e:\\USER\\Downloads\\Edvankar\\public\\images\\qwikamp\\diagram_1_system_overview_blueprint.png');
  const artifactPng = 'C:\\Users\\USER\\.gemini\\antigravity-ide\\brain\\ef2fb206-3666-42f6-b9f4-231cc94dc87e\\diagram_1_system_overview_blueprint.png';

  const chromePath = 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';

  console.log('Rendering 2560x1440 PNG using headless Chrome...');
  const cmd = `"${chromePath}" --headless=new --screenshot="${outPng1}" --window-size=2560,1440 --default-background-color=0C0E12 "file:///${htmlPath.replace(/\\/g, '/')}"`;

  execSync(cmd, { stdio: 'inherit' });

  if (fs.existsSync(outPng1)) {
    const size = fs.statSync(outPng1).size;
    console.log(`Successfully generated rustic blueprint PNG at: ${outPng1} (${(size / 1024).toFixed(1)} KB)`);
    fs.copyFileSync(outPng1, outPng2);
    fs.copyFileSync(outPng1, artifactPng);
    console.log(`Copied to public and artifact directories.`);
  }
}

run().catch(err => {
  console.error(err);
  process.exit(1);
});
